change to utf-8 and see if this fixes issue with old visual c compiler yielding 'main.c : error C4335: Mac file format detected: please convert the source file to either DOS or UNIX format'